### PR TITLE
replaced mkdocs docker image

### PR DESCRIPTION
**Pull request by tuxerrante**

### CODE REVIEW

**Comment by vfarcic** [comment]
`docker image build...` is failing...

```
...
Step 5/8 : RUN mkdocs build --site-dir /site
 ---> Running in 6b5bdceff80f

Config file '/workdir/mkdocs.yml' does not exist.
```

**Comment by tuxerrante** [comment]
Hi,
I will try to look into this, this evening..

**Comment by tuxerrante** [comment]
Hi Viktor,
I think I fixed the issue, would you like to reopen this or should I open a new PR?

It was missing a  `mkdocs new mkdocs` to initialize the mkdocs.yml file.
Also the `ADD . /docs` was having no effect.

I have rebuilt the mkdocs image from a python3:alpine image like that:
```
FROM python:3.7-alpine3.10 AS build

ENV MKDOCS_VERSION="1.0.4" \
    GIT_REPO='false' \
    LIVE_RELOAD_SUPPORT='false'

RUN \
    apk add --update --no-cache  \
        ca-certificates \
        bash \
        git \
        openssh ;  \
    pip install mkdocs==${MKDOCS_VERSION} && \
    rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/*

RUN mkdir /workdir && cd /workdir   && \
    pip install pygments pymdown-extensions   && \
    mkdocs new mkdocs

ADD ./docs /workdir/mkdocs/docs
WORKDIR /workdir/mkdocs

RUN  mkdocs build --site-dir /site
```

I have also left a python2 compatible Dockerfile_py2.docs.

**Comment by vfarcic** [comment]
I already merged this PR so I cannot reopen it. Can you make a new one?

**Comment by tuxerrante** [comment]
Done!

**Pull request merged**
